version: '2'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: praise-io
    volumes:
      - ./docker/db/data:/var/lib/mysql
  web:
    image: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx/sites/local.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/local.default.conf:/etc/nginx/local.default.conf
    links:
      - php

  php:
    extends:
      file: ./docker/base-php/base-php.yml
      service: base-php
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    links:
      - db