version: '2'
services:
  php:
    build: .
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
#      - .:/var/www/html
      - ./vhost.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - '8080:80'